# .github/workflows/nodejs.yml
name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [10]
        os: [centos-latest]

    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        env:
          ACCESSKEYID: ${{ secrets.ACCESSKEYID }}
          ACCESSKEYSECRET: ${{ secrets.ACCESSKEYSECRET }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          # key: ${{ secrets.KEY }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: ACCESSKEYID,ACCESSKEYSECRET
          script: |
            export ACCESSKEYID=$ACCESSKEYID
            export ACCESSKEYSECRET=$ACCESSKEYSECRET
            cd /root/youtubeclone-backend
            git pull origin main
            npm install --production
            npm run stop
            npm run start
